In [20]:
import pandas as pd

df = pd.read_csv("2_data cleaning/BankChurners.csv")

df.columns

Index(['CLIENTNUM', 'Attrition_Flag', 'Customer_Age', 'Gender',
       'Dependent_count', 'Education_Level', 'Marital_Status',
       'Income_Category', 'Card_Category', 'Months_on_book',
       'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'],
      dtype='object')

In [26]:
columns = df.columns

for column in columns:
    print(f"The different unique data in the column named :'{column}' are :")
    values = df[column].sort_values().unique()
    display(f"{values}")
    print(f"There are {len(values)} different values in this column\n\n")

The different unique data in the column named :'CLIENTNUM' are :

'[708082083 708083283 708084558 ... 828294933 828298908 828343083]'

There are 10127 different values in this column


The different unique data in the column named :'Attrition_Flag' are :

"['Attrited Customer' 'Existing Customer']"

There are 2 different values in this column


The different unique data in the column named :'Customer_Age' are :

'[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49\n 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 70 73]'

There are 45 different values in this column


The different unique data in the column named :'Gender' are :

"['F' 'M']"

There are 2 different values in this column


The different unique data in the column named :'Dependent_count' are :

'[0 1 2 3 4 5]'

There are 6 different values in this column


The different unique data in the column named :'Education_Level' are :

"['College' 'Doctorate' 'Graduate' 'High School' 'Post-Graduate'\n 'Uneducated' 'Unknown']"

There are 7 different values in this column


The different unique data in the column named :'Marital_Status' are :

"['Divorced' 'Married' 'Single' 'Unknown']"

There are 4 different values in this column


The different unique data in the column named :'Income_Category' are :

"['$120K +' '$40K - $60K' '$60K - $80K' '$80K - $120K' 'Less than $40K'\n 'Unknown']"

There are 6 different values in this column


The different unique data in the column named :'Card_Category' are :

"['Blue' 'Gold' 'Platinum' 'Silver']"

There are 4 different values in this column


The different unique data in the column named :'Months_on_book' are :

'[13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36\n 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56]'

There are 44 different values in this column


The different unique data in the column named :'Total_Relationship_Count' are :

'[1 2 3 4 5 6]'

There are 6 different values in this column


The different unique data in the column named :'Months_Inactive_12_mon' are :

'[0 1 2 3 4 5 6]'

There are 7 different values in this column


The different unique data in the column named :'Contacts_Count_12_mon' are :

'[0 1 2 3 4 5 6]'

There are 7 different values in this column


The different unique data in the column named :'Credit_Limit' are :

'[ 1438.3  1439.   1440.  ... 34458.  34496.  34516. ]'

There are 6205 different values in this column


The different unique data in the column named :'Total_Revolving_Bal' are :

'[   0  132  134 ... 2513 2514 2517]'

There are 1974 different values in this column


The different unique data in the column named :'Avg_Open_To_Buy' are :

'[3.0000e+00 1.0000e+01 1.4000e+01 ... 3.4302e+04 3.4362e+04 3.4516e+04]'

There are 6813 different values in this column


The different unique data in the column named :'Total_Amt_Chng_Q4_Q1' are :

'[0.    0.01  0.018 ... 2.675 3.355 3.397]'

There are 1158 different values in this column


The different unique data in the column named :'Total_Trans_Amt' are :

'[  510   530   563 ... 17744 17995 18484]'

There are 5033 different values in this column


The different unique data in the column named :'Total_Trans_Ct' are :

'[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27\n  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45\n  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63\n  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81\n  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99\n 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117\n 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 134 138 139]'

There are 126 different values in this column


The different unique data in the column named :'Total_Ct_Chng_Q4_Q1' are :

'[0.    0.028 0.029 0.038 0.053 0.059 0.062 0.074 0.077 0.091 0.097 0.103\n 0.105 0.107 0.111 0.119 0.125 0.13  0.133 0.143 0.147 0.15  0.154 0.161\n 0.162 0.167 0.171 0.172 0.174 0.176 0.179 0.182 0.185 0.188 0.189 0.19\n 0.192 0.194 0.2   0.206 0.207 0.208 0.211 0.212 0.214 0.217 0.222 0.226\n 0.227 0.231 0.233 0.235 0.238 0.24  0.241 0.242 0.244 0.25  0.256 0.257\n 0.259 0.261 0.262 0.263 0.265 0.267 0.269 0.273 0.275 0.276 0.278 0.28\n 0.281 0.282 0.286 0.29  0.292 0.293 0.294 0.295 0.296 0.297 0.3   0.303\n 0.304 0.306 0.308 0.31  0.312 0.314 0.316 0.317 0.318 0.32  0.321 0.323\n 0.324 0.327 0.333 0.341 0.343 0.344 0.345 0.346 0.347 0.348 0.349 0.35\n 0.351 0.353 0.355 0.357 0.359 0.36  0.361 0.362 0.364 0.367 0.368 0.37\n 0.371 0.372 0.375 0.378 0.379 0.381 0.382 0.385 0.387 0.388 0.389 0.391\n 0.393 0.394 0.395 0.396 0.4   0.405 0.406 0.407 0.408 0.409 0.41  0.411\n 0.412 0.414 0.415 0.417 0.419 0.421 0.422 0.423 0.424 0.425 0.426 0.429\n 0.431 0.432 0.433 0.434 0.435 0.436 0.438 0.439 0.44  0.441 0.442 0.444\n 0.447 0.448 0.449 0.45  0.451 0.452 0.453 0.455 0.456 0.457 0.458 0.459\n 0.46  0.462 0.463 0.464 0.465 0.467 0.468 0.469 0.471 0.472 0.473 0.474\n 0.475 0.476 0.477 0.478 0.479 0.48  0.481 0.483 0.484 0.485 0.486 0.487\n 0.488 0.489 0.49  0.491 0.492 0.5   0.508 0.509 0.51  0.511 0.512 0.513\n 0.514 0.515 0.516 0.517 0.518 0.519 0.52  0.521 0.522 0.523 0.524 0.525\n 0.526 0.527 0.528 0.529 0.531 0.532 0.533 0.534 0.535 0.536 0.537 0.538\n 0.54  0.541 0.542 0.543 0.544 0.545 0.547 0.548 0.549 0.55  0.551 0.552\n 0.553 0.554 0.556 0.557 0.558 0.559 0.56  0.561 0.562 0.564 0.565 0.566\n 0.567 0.568 0.569 0.571 0.573 0.574 0.575 0.576 0.577 0.578 0.579 0.58\n 0.581 0.582 0.583 0.585 0.586 0.587 0.588 0.589 0.59  0.591 0.592 0.593\n 0.594 0.595 0.596 0.597 0.6   0.603 0.604 0.605 0.606 0.607 0.608 0.609\n 0.61  0.611 0.612 0.613 0.614 0.615 0.616 0.617 0.618 0.619 0.62  0.621\n 0.622 0.623 0.625 0.627 0.628 0.629 0.63  0.631 0.632 0.633 0.634 0.635\n 0.636 0.638 0.639 0.64  0.641 0.642 0.643 0.644 0.645 0.646 0.647 0.648\n 0.649 0.65  0.651 0.652 0.653 0.654 0.655 0.656 0.657 0.658 0.659 0.66\n 0.661 0.662 0.667 0.671 0.672 0.673 0.674 0.675 0.676 0.677 0.678 0.679\n 0.68  0.681 0.682 0.683 0.684 0.685 0.686 0.687 0.688 0.689 0.69  0.691\n 0.692 0.693 0.694 0.695 0.696 0.697 0.698 0.699 0.7   0.702 0.703 0.704\n 0.705 0.706 0.707 0.708 0.709 0.71  0.711 0.712 0.714 0.716 0.717 0.718\n 0.719 0.72  0.721 0.722 0.723 0.724 0.725 0.726 0.727 0.729 0.73  0.731\n 0.732 0.733 0.734 0.735 0.736 0.737 0.738 0.739 0.74  0.741 0.742 0.743\n 0.744 0.745 0.746 0.75  0.753 0.754 0.755 0.756 0.757 0.758 0.759 0.76\n 0.761 0.762 0.763 0.764 0.765 0.766 0.767 0.768 0.769 0.77  0.771 0.772\n 0.773 0.774 0.775 0.776 0.778 0.779 0.78  0.781 0.782 0.783 0.784 0.785\n 0.786 0.787 0.788 0.789 0.79  0.791 0.792 0.793 0.794 0.795 0.796 0.797\n 0.8   0.803 0.804 0.805 0.806 0.807 0.808 0.809 0.81  0.811 0.812 0.814\n 0.815 0.816 0.817 0.818 0.819 0.82  0.821 0.822 0.823 0.824 0.825 0.826\n 0.827 0.828 0.829 0.83  0.831 0.833 0.836 0.837 0.838 0.839 0.84  0.841\n 0.842 0.843 0.844 0.846 0.847 0.848 0.849 0.85  0.851 0.852 0.853 0.854\n 0.855 0.857 0.859 0.86  0.861 0.862 0.863 0.864 0.865 0.866 0.867 0.868\n 0.869 0.87  0.871 0.872 0.873 0.875 0.878 0.879 0.88  0.881 0.882 0.884\n 0.885 0.886 0.887 0.889 0.891 0.892 0.893 0.894 0.895 0.896 0.897 0.898\n 0.9   0.902 0.903 0.905 0.906 0.907 0.909 0.911 0.912 0.913 0.914 0.915\n 0.917 0.918 0.919 0.92  0.921 0.922 0.923 0.925 0.926 0.927 0.929 0.93\n 0.931 0.932 0.933 0.934 0.935 0.936 0.938 0.939 0.941 0.943 0.944 0.946\n 0.947 0.948 0.949 0.95  0.951 0.952 0.953 0.955 0.956 0.957 0.958 0.96\n 0.962 0.963 0.964 0.966 0.967 0.968 0.969 0.97  0.971 0.972 0.973 0.974\n 0.975 0.976 0.977 0.978 0.98  0.981 1.    1.018 1.022 1.023 1.024 1.025\n 1.026 1.027 1.028 1.029 1.03  1.031 1.032 1.033 1.034 1.036 1.037 1.038\n 1.04  1.042 1.043 1.045 1.048 1.049 1.05  1.051 1.053 1.054 1.056 1.057\n 1.059 1.06  1.061 1.062 1.064 1.065 1.067 1.069 1.071 1.073 1.074 1.075\n 1.077 1.079 1.08  1.081 1.083 1.086 1.087 1.088 1.091 1.093 1.094 1.095\n 1.097 1.1   1.103 1.105 1.107 1.108 1.111 1.114 1.115 1.118 1.12  1.121\n 1.122 1.125 1.128 1.13  1.133 1.135 1.136 1.138 1.139 1.143 1.147 1.148\n 1.15  1.152 1.154 1.156 1.158 1.16  1.161 1.162 1.167 1.171 1.172 1.174\n 1.176 1.179 1.182 1.188 1.189 1.194 1.2   1.206 1.207 1.208 1.211 1.212\n 1.214 1.217 1.219 1.222 1.226 1.227 1.229 1.231 1.235 1.24  1.25  1.258\n 1.263 1.273 1.278 1.286 1.29  1.292 1.294 1.3   1.303 1.308 1.31  1.312\n 1.316 1.318 1.32  1.321 1.323 1.333 1.346 1.35  1.357 1.36  1.364 1.367\n 1.37  1.375 1.381 1.382 1.385 1.391 1.4   1.412 1.417 1.419 1.421 1.429\n 1.438 1.444 1.45  1.455 1.458 1.462 1.467 1.471 1.474 1.476 1.478 1.48\n 1.5   1.522 1.533 1.538 1.545 1.571 1.579 1.583 1.6   1.609 1.615 1.625\n 1.636 1.647 1.65  1.667 1.684 1.7   1.722 1.75  1.778 1.783 1.8   1.833\n 1.857 1.875 1.882 1.909 1.923 2.    2.083 2.1   2.167 2.182 2.2   2.222\n 2.273 2.286 2.333 2.4   2.429 2.5   2.571 2.75  2.875 3.    3.25  3.5\n 3.571 3.714]'

There are 830 different values in this column


The different unique data in the column named :'Avg_Utilization_Ratio' are :

'[0.    0.004 0.005 0.006 0.007 0.008 0.009 0.01  0.011 0.012 0.013 0.014\n 0.015 0.016 0.017 0.018 0.019 0.02  0.021 0.022 0.023 0.024 0.025 0.026\n 0.027 0.028 0.029 0.03  0.031 0.032 0.033 0.034 0.035 0.036 0.037 0.038\n 0.039 0.04  0.041 0.042 0.043 0.044 0.045 0.046 0.047 0.048 0.049 0.05\n 0.051 0.052 0.053 0.054 0.055 0.056 0.057 0.058 0.059 0.06  0.061 0.062\n 0.063 0.064 0.065 0.066 0.067 0.068 0.069 0.07  0.071 0.072 0.073 0.074\n 0.075 0.076 0.077 0.078 0.079 0.08  0.081 0.082 0.083 0.084 0.085 0.086\n 0.087 0.088 0.089 0.09  0.091 0.092 0.093 0.094 0.095 0.096 0.097 0.098\n 0.099 0.1   0.101 0.102 0.103 0.104 0.105 0.106 0.107 0.108 0.109 0.11\n 0.111 0.112 0.113 0.114 0.115 0.116 0.117 0.118 0.119 0.12  0.121 0.122\n 0.123 0.124 0.125 0.126 0.127 0.128 0.129 0.13  0.131 0.132 0.133 0.134\n 0.135 0.136 0.137 0.138 0.139 0.14  0.141 0.142 0.143 0.144 0.145 0.146\n 0.147 0.148 0.149 0.15  0.151 0.152 0.153 0.154 0.155 0.156 0.157 0.158\n 0.159 0.16  0.161 0.162 0.163 0.164 0.165 0.166 0.167 0.168 0.169 0.17\n 0.171 0.172 0.173 0.174 0.175 0.176 0.177 0.178 0.179 0.18  0.181 0.182\n 0.183 0.184 0.185 0.186 0.187 0.188 0.189 0.19  0.191 0.192 0.193 0.194\n 0.195 0.196 0.197 0.198 0.199 0.2   0.201 0.202 0.203 0.204 0.205 0.206\n 0.207 0.208 0.209 0.21  0.211 0.212 0.213 0.214 0.215 0.216 0.217 0.218\n 0.219 0.22  0.221 0.222 0.223 0.224 0.225 0.226 0.227 0.228 0.229 0.23\n 0.231 0.232 0.233 0.234 0.235 0.236 0.237 0.238 0.239 0.24  0.241 0.242\n 0.243 0.244 0.245 0.246 0.247 0.248 0.249 0.25  0.251 0.252 0.253 0.254\n 0.255 0.256 0.257 0.258 0.259 0.26  0.261 0.262 0.263 0.264 0.265 0.266\n 0.267 0.268 0.269 0.27  0.271 0.272 0.273 0.274 0.275 0.276 0.277 0.278\n 0.279 0.28  0.281 0.282 0.283 0.284 0.285 0.286 0.287 0.288 0.289 0.29\n 0.291 0.292 0.293 0.294 0.295 0.296 0.297 0.298 0.299 0.3   0.301 0.302\n 0.303 0.304 0.305 0.306 0.307 0.308 0.309 0.31  0.311 0.312 0.313 0.314\n 0.315 0.316 0.317 0.318 0.319 0.32  0.321 0.322 0.323 0.324 0.325 0.326\n 0.327 0.328 0.329 0.33  0.331 0.332 0.333 0.334 0.335 0.336 0.337 0.338\n 0.339 0.34  0.341 0.342 0.343 0.344 0.345 0.346 0.347 0.348 0.349 0.35\n 0.351 0.352 0.353 0.354 0.355 0.356 0.357 0.358 0.359 0.36  0.361 0.362\n 0.363 0.364 0.365 0.366 0.367 0.368 0.369 0.37  0.371 0.372 0.373 0.374\n 0.375 0.376 0.377 0.378 0.379 0.38  0.381 0.382 0.383 0.384 0.385 0.386\n 0.387 0.388 0.389 0.39  0.391 0.392 0.393 0.394 0.395 0.396 0.397 0.398\n 0.399 0.4   0.401 0.402 0.403 0.404 0.405 0.406 0.407 0.408 0.409 0.41\n 0.411 0.412 0.413 0.414 0.415 0.416 0.417 0.418 0.419 0.42  0.421 0.422\n 0.423 0.424 0.425 0.426 0.427 0.428 0.429 0.43  0.431 0.432 0.433 0.434\n 0.435 0.436 0.437 0.438 0.439 0.44  0.441 0.442 0.443 0.444 0.445 0.446\n 0.447 0.448 0.449 0.45  0.451 0.452 0.453 0.454 0.455 0.456 0.457 0.458\n 0.459 0.46  0.461 0.462 0.463 0.464 0.465 0.466 0.467 0.468 0.469 0.47\n 0.471 0.472 0.473 0.474 0.475 0.476 0.477 0.478 0.479 0.48  0.481 0.482\n 0.483 0.484 0.485 0.486 0.487 0.488 0.489 0.49  0.491 0.492 0.493 0.494\n 0.495 0.496 0.497 0.498 0.499 0.5   0.501 0.502 0.503 0.504 0.505 0.506\n 0.507 0.508 0.509 0.51  0.511 0.512 0.513 0.514 0.515 0.516 0.517 0.518\n 0.519 0.52  0.521 0.522 0.523 0.524 0.525 0.526 0.527 0.528 0.529 0.53\n 0.531 0.532 0.533 0.534 0.535 0.536 0.537 0.538 0.539 0.54  0.541 0.542\n 0.543 0.544 0.545 0.546 0.547 0.548 0.549 0.55  0.551 0.552 0.553 0.554\n 0.555 0.556 0.557 0.558 0.559 0.56  0.561 0.562 0.563 0.564 0.565 0.566\n 0.567 0.568 0.569 0.57  0.571 0.572 0.573 0.574 0.575 0.576 0.577 0.578\n 0.579 0.58  0.581 0.582 0.583 0.584 0.585 0.586 0.587 0.588 0.589 0.59\n 0.591 0.592 0.593 0.594 0.595 0.596 0.597 0.598 0.599 0.6   0.601 0.602\n 0.603 0.604 0.605 0.606 0.607 0.608 0.609 0.61  0.611 0.612 0.613 0.614\n 0.615 0.616 0.617 0.618 0.619 0.62  0.621 0.622 0.623 0.624 0.625 0.626\n 0.627 0.628 0.629 0.63  0.631 0.632 0.633 0.634 0.635 0.636 0.637 0.638\n 0.639 0.64  0.641 0.642 0.643 0.644 0.645 0.646 0.647 0.648 0.649 0.65\n 0.651 0.652 0.653 0.654 0.655 0.656 0.657 0.658 0.659 0.66  0.661 0.662\n 0.663 0.664 0.665 0.666 0.667 0.668 0.669 0.67  0.671 0.672 0.673 0.674\n 0.675 0.676 0.677 0.678 0.679 0.68  0.681 0.682 0.683 0.684 0.685 0.686\n 0.687 0.688 0.689 0.69  0.691 0.692 0.693 0.694 0.695 0.696 0.697 0.698\n 0.699 0.7   0.701 0.702 0.703 0.704 0.705 0.706 0.707 0.708 0.709 0.71\n 0.711 0.712 0.713 0.714 0.715 0.716 0.717 0.718 0.719 0.72  0.721 0.722\n 0.723 0.724 0.725 0.726 0.727 0.728 0.729 0.73  0.731 0.732 0.733 0.734\n 0.735 0.736 0.737 0.738 0.739 0.74  0.741 0.742 0.743 0.744 0.745 0.746\n 0.747 0.748 0.749 0.75  0.751 0.752 0.753 0.754 0.755 0.756 0.757 0.758\n 0.759 0.76  0.761 0.762 0.763 0.764 0.765 0.766 0.767 0.768 0.769 0.77\n 0.771 0.772 0.773 0.774 0.775 0.776 0.777 0.778 0.779 0.78  0.781 0.782\n 0.783 0.784 0.785 0.786 0.787 0.788 0.789 0.79  0.791 0.792 0.793 0.794\n 0.795 0.796 0.797 0.798 0.799 0.8   0.801 0.802 0.803 0.804 0.805 0.806\n 0.807 0.808 0.809 0.81  0.811 0.812 0.813 0.814 0.815 0.816 0.817 0.818\n 0.819 0.82  0.821 0.822 0.823 0.824 0.825 0.826 0.827 0.828 0.829 0.83\n 0.831 0.832 0.833 0.834 0.835 0.836 0.837 0.839 0.84  0.841 0.842 0.843\n 0.844 0.845 0.846 0.847 0.848 0.849 0.85  0.851 0.852 0.853 0.854 0.855\n 0.856 0.857 0.858 0.859 0.86  0.861 0.862 0.863 0.864 0.865 0.866 0.867\n 0.868 0.869 0.87  0.871 0.872 0.873 0.874 0.875 0.876 0.877 0.878 0.879\n 0.88  0.881 0.882 0.883 0.884 0.885 0.886 0.887 0.889 0.891 0.893 0.894\n 0.895 0.896 0.897 0.898 0.899 0.9   0.901 0.902 0.903 0.904 0.905 0.906\n 0.907 0.909 0.91  0.911 0.912 0.913 0.914 0.915 0.916 0.917 0.918 0.919\n 0.92  0.921 0.922 0.924 0.925 0.926 0.927 0.928 0.929 0.93  0.931 0.932\n 0.934 0.935 0.938 0.94  0.941 0.942 0.943 0.944 0.945 0.948 0.949 0.951\n 0.952 0.953 0.954 0.955 0.956 0.958 0.959 0.96  0.962 0.963 0.964 0.968\n 0.971 0.972 0.973 0.976 0.977 0.978 0.983 0.984 0.985 0.987 0.988 0.99\n 0.992 0.994 0.995 0.999]'

There are 964 different values in this column


The different unique data in the column named :'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1' are :

'[7.6642e-06 7.7559e-06 1.0252e-05 ... 9.9945e-01 9.9954e-01 9.9958e-01]'

There are 1704 different values in this column


The different unique data in the column named :'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2' are :

'[4.19980e-04 4.24460e-04 4.62370e-04 5.52850e-04 5.58750e-04 5.61600e-04\n 5.61810e-04 5.69020e-04 5.79790e-04 5.83610e-04 6.07650e-04 6.14140e-04\n 6.17270e-04 6.17670e-04 6.19800e-04 6.25370e-04 6.31740e-04 6.37270e-04\n 6.46540e-04 6.60300e-04 6.72470e-04 6.78900e-04 6.98280e-04 7.63820e-04\n 8.02750e-04 8.24690e-04 8.71710e-04 8.82310e-04 9.00530e-04 9.12270e-04\n 9.33700e-04 9.59770e-04 9.67430e-04 9.70000e-04 9.70260e-04 9.78870e-04\n 9.80360e-04 9.85350e-04 9.87500e-04 9.98040e-04 1.00312e-03 1.00677e-03\n 1.01395e-03 1.01725e-03 1.03551e-03 1.04314e-03 1.04747e-03 1.04798e-03\n 1.06129e-03 1.06195e-03 1.06612e-03 1.06650e-03 1.07750e-03 1.08299e-03\n 1.08359e-03 1.08742e-03 1.09664e-03 1.10835e-03 1.11805e-03 1.12034e-03\n 1.14090e-03 1.15006e-03 1.19106e-03 1.19984e-03 1.22089e-03 1.26699e-03\n 1.27462e-03 1.28822e-03 1.28895e-03 1.29704e-03 1.30267e-03 1.33669e-03\n 1.37244e-03 1.43279e-03 1.44667e-03 1.47930e-03 1.49992e-03 1.52587e-03\n 1.54215e-03 1.54849e-03 1.55100e-03 1.55634e-03 1.55735e-03 1.56939e-03\n 1.56953e-03 1.58385e-03 1.59436e-03 1.59907e-03 1.60016e-03 1.62275e-03\n 1.64342e-03 1.64579e-03 1.64594e-03 1.65082e-03 1.65524e-03 1.65792e-03\n 1.67742e-03 1.68378e-03 1.69532e-03 1.70460e-03 1.75053e-03 1.75068e-03\n 1.75321e-03 1.75907e-03 1.76584e-03 1.77065e-03 1.79304e-03 1.81217e-03\n 1.81320e-03 1.82139e-03 1.84351e-03 1.84416e-03 1.86317e-03 1.87266e-03\n 1.87387e-03 1.87593e-03 1.87699e-03 1.88031e-03 1.88108e-03 1.88594e-03\n 1.89625e-03 1.89674e-03 1.89855e-03 1.91630e-03 1.91647e-03 1.91756e-03\n 1.93323e-03 1.93489e-03 1.97641e-03 1.98404e-03 1.98835e-03 1.98853e-03\n 2.00300e-03 2.00900e-03 2.01294e-03 2.01684e-03 2.02158e-03 2.05937e-03\n 2.06163e-03 2.07303e-03 2.09822e-03 2.11089e-03 2.11605e-03 2.11807e-03\n 2.11827e-03 2.12041e-03 2.12180e-03 2.17267e-03 2.19052e-03 2.19584e-03\n 2.19708e-03 2.20011e-03 2.21086e-03 2.23444e-03 2.25216e-03 2.27837e-03\n 2.31656e-03 2.31842e-03 2.34362e-03 2.36635e-03 2.39178e-03 2.42697e-03\n 2.48146e-03 2.50084e-03 2.51777e-03 2.52095e-03 2.52933e-03 2.55630e-03\n 2.56930e-03 2.58725e-03 2.59482e-03 2.60048e-03 2.62820e-03 2.64844e-03\n 2.65290e-03 2.65408e-03 2.67072e-03 2.67481e-03 2.67667e-03 2.69029e-03\n 2.70308e-03 2.70332e-03 2.71291e-03 2.71707e-03 2.72694e-03 2.75658e-03\n 2.76400e-03 2.77723e-03 2.80059e-03 2.80463e-03 2.80488e-03 2.82527e-03\n 2.83080e-03 2.84317e-03 2.85845e-03 2.86013e-03 2.86097e-03 2.88892e-03\n 2.89056e-03 2.90361e-03 2.90471e-03 2.91040e-03 2.94141e-03 2.94187e-03\n 2.94997e-03 2.95494e-03 2.95637e-03 2.95827e-03 2.96843e-03 2.98315e-03\n 2.98772e-03 2.99329e-03 2.99357e-03 2.99743e-03 3.02519e-03 3.02546e-03\n 3.03398e-03 3.03426e-03 3.05189e-03 3.05345e-03 3.05523e-03 3.05631e-03\n 3.08778e-03 3.09859e-03 3.10334e-03 3.10348e-03 3.13880e-03 3.13909e-03\n 3.14112e-03 3.14223e-03 3.16131e-03 3.16190e-03 3.16259e-03 3.17458e-03\n 3.17639e-03 3.19072e-03 3.19278e-03 3.20374e-03 3.22004e-03 3.23056e-03\n 3.23086e-03 3.23171e-03 3.23200e-03 3.23494e-03 3.25077e-03 3.26213e-03\n 3.26498e-03 3.26528e-03 3.26683e-03 3.26713e-03 3.28158e-03 3.28187e-03\n 3.29379e-03 3.34333e-03 3.34364e-03 3.37654e-03 3.38757e-03 3.38788e-03\n 3.41249e-03 3.42939e-03 3.45754e-03 3.46592e-03 3.48354e-03 3.49130e-03\n 3.50838e-03 3.54449e-03 3.54519e-03 3.55470e-03 3.57448e-03 3.59603e-03\n 3.59650e-03 3.60825e-03 3.60858e-03 3.61075e-03 3.61108e-03 3.61221e-03\n 3.61254e-03 3.61426e-03 3.64408e-03 3.64906e-03 3.65621e-03 3.68792e-03\n 3.69001e-03 3.73147e-03 3.74779e-03 3.75265e-03 3.77382e-03 3.82633e-03\n 3.83630e-03 3.88140e-03 3.91691e-03 3.94546e-03 3.94582e-03 4.05509e-03\n 4.07548e-03 4.16681e-03 4.16767e-03 4.16897e-03 4.18811e-03 4.24232e-03\n 4.24404e-03 4.25916e-03 4.31907e-03 4.34923e-03 4.36631e-03 4.37002e-03\n 4.41277e-03 4.41892e-03 4.43518e-03 4.43803e-03 4.44033e-03 4.45417e-03\n 4.45616e-03 4.48403e-03 4.51007e-03 4.51271e-03 4.53174e-03 4.53431e-03\n 4.53868e-03 4.55475e-03 4.55805e-03 4.57826e-03 4.58119e-03 4.62792e-03\n 4.64271e-03 4.70167e-03 4.70647e-03 4.70886e-03 4.72896e-03 4.74303e-03\n 4.79863e-03 4.81678e-03 4.81999e-03 4.83011e-03 4.84967e-03 4.85493e-03\n 4.87126e-03 4.87428e-03 4.90915e-03 4.94341e-03 4.95524e-03 4.99338e-03\n 5.01000e-03 5.03000e-03 5.04000e-03 5.05000e-03 5.07000e-03 5.10000e-03\n 5.13000e-03 5.15000e-03 5.18000e-03 5.20000e-03 5.23000e-03 5.27000e-03\n 5.28000e-03 5.33000e-03 5.34000e-03 5.36000e-03 5.38000e-03 5.42000e-03\n 5.47000e-03 5.48000e-03 5.51000e-03 5.53000e-03 5.59000e-03 5.62000e-03\n 5.68000e-03 5.69000e-03 5.70000e-03 5.72000e-03 5.73000e-03 5.75000e-03\n 5.76000e-03 5.82000e-03 5.83000e-03 5.85000e-03 5.86000e-03 5.89000e-03\n 5.91000e-03 5.92000e-03 5.95000e-03 6.00000e-03 6.03000e-03 6.05000e-03\n 6.06000e-03 6.09000e-03 6.10000e-03 6.11000e-03 6.21000e-03 6.22000e-03\n 6.26000e-03 6.29000e-03 6.43000e-03 6.44000e-03 6.57000e-03 6.62000e-03\n 6.68000e-03 6.69000e-03 6.70000e-03 6.74000e-03 6.78000e-03 6.80000e-03\n 7.02000e-03 7.07000e-03 7.14000e-03 7.19000e-03 7.30000e-03 7.32000e-03\n 7.40000e-03 7.41000e-03 7.49000e-03 7.50000e-03 7.53000e-03 7.56000e-03\n 7.64000e-03 7.77000e-03 7.88000e-03 7.89000e-03 7.90000e-03 7.92000e-03\n 7.93000e-03 8.02000e-03 8.08000e-03 8.11000e-03 8.17000e-03 8.21000e-03\n 8.29000e-03 8.31000e-03 8.32000e-03 8.33000e-03 8.36000e-03 8.37000e-03\n 8.39000e-03 8.42000e-03 8.44000e-03 8.47000e-03 8.48000e-03 8.54000e-03\n 8.57000e-03 8.63000e-03 8.68000e-03 8.71000e-03 8.76000e-03 8.77000e-03\n 8.80000e-03 8.89000e-03 8.94000e-03 8.95000e-03 8.96000e-03 9.02000e-03\n 9.05000e-03 9.10000e-03 9.13000e-03 9.27000e-03 9.28000e-03 9.37000e-03\n 9.39000e-03 9.45000e-03 9.51000e-03 9.53000e-03 9.54000e-03 9.68000e-03\n 9.69000e-03 9.72000e-03 9.74000e-03 9.86000e-03 9.97000e-03 1.00000e-02\n 1.01300e-02 1.01900e-02 1.02900e-02 1.03500e-02 1.03900e-02 1.04200e-02\n 1.05800e-02 1.05900e-02 1.06300e-02 1.06400e-02 1.06800e-02 1.09300e-02\n 1.09800e-02 1.12600e-02 1.13100e-02 1.13700e-02 1.15800e-02 1.16900e-02\n 1.18000e-02 1.20900e-02 1.24900e-02 1.26100e-02 1.27700e-02 1.29000e-02\n 1.29300e-02 1.30400e-02 1.30800e-02 1.33300e-02 1.37000e-02 1.38100e-02\n 1.38400e-02 1.39200e-02 1.39700e-02 1.40900e-02 1.42400e-02 1.43600e-02\n 1.46500e-02 1.47200e-02 1.48500e-02 1.48700e-02 1.49600e-02 1.52800e-02\n 1.53200e-02 1.56700e-02 1.57100e-02 1.62500e-02 1.63100e-02 1.67300e-02\n 1.68100e-02 1.72000e-02 1.72900e-02 1.73500e-02 1.78300e-02 1.83300e-02\n 1.83900e-02 1.84100e-02 1.84600e-02 1.89800e-02 1.91700e-02 1.95100e-02\n 2.13000e-02 2.39100e-02 2.57200e-02 2.66100e-02 2.73400e-02 2.75900e-02\n 2.82000e-02 2.83400e-02 2.84500e-02 2.86800e-02 2.93400e-02 3.09800e-02\n 3.19400e-02 3.31000e-02 3.39000e-02 4.80500e-02 5.40900e-02 9.98680e-01\n 9.98710e-01 9.98770e-01 9.98950e-01 9.98970e-01 9.98980e-01 9.99020e-01\n 9.99050e-01 9.99060e-01 9.99070e-01 9.99080e-01 9.99100e-01 9.99130e-01\n 9.99140e-01 9.99160e-01 9.99170e-01 9.99180e-01 9.99190e-01 9.99210e-01\n 9.99220e-01 9.99230e-01 9.99250e-01 9.99260e-01 9.99270e-01 9.99290e-01\n 9.99300e-01 9.99310e-01 9.99320e-01 9.99330e-01 9.99340e-01 9.99350e-01\n 9.99360e-01 9.99370e-01 9.99380e-01 9.99390e-01 9.99400e-01 9.99410e-01\n 9.99420e-01 9.99430e-01 9.99440e-01 9.99450e-01 9.99460e-01 9.99470e-01\n 9.99480e-01 9.99490e-01 9.99500e-01 9.99510e-01 9.99520e-01 9.99530e-01\n 9.99540e-01 9.99550e-01 9.99560e-01 9.99570e-01 9.99580e-01 9.99590e-01\n 9.99600e-01 9.99610e-01 9.99620e-01 9.99630e-01 9.99640e-01 9.99650e-01\n 9.99660e-01 9.99670e-01 9.99680e-01 9.99690e-01 9.99700e-01 9.99710e-01\n 9.99720e-01 9.99730e-01 9.99740e-01 9.99750e-01 9.99760e-01 9.99770e-01\n 9.99780e-01 9.99790e-01 9.99800e-01 9.99810e-01 9.99820e-01 9.99830e-01\n 9.99840e-01 9.99850e-01 9.99860e-01 9.99870e-01 9.99880e-01 9.99890e-01\n 9.99900e-01 9.99910e-01 9.99920e-01 9.99930e-01 9.99940e-01 9.99950e-01\n 9.99960e-01 9.99970e-01 9.99980e-01 9.99990e-01]'

There are 640 different values in this column

In [17]:
df['Customer_Age'].sort_values().unique()

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 68, 70, 73])